### ISSUE TITLE
Add images with the items

### ISSUE THREAD

**Issue by gamma-delta** [gamma-delta/center-brain-archive#2]
I suspect I could do this with CSS `::before` or something... but mostly I need a way to download all the thumbnails.

Anyone know where I can get them? Am I allowed to download from the wiki, or use their images cross-site without having to copy them locally?

**Comment by mellester** [comment]
I can tell you the following.
https://github.com/factoriolab/factorio-lab/tree/master/src/data/dsp and 
https://github.com/factoriolab/factorio-lab/blob/master/src/data/dsp/icons.png
Is were I pulled the data for my last PR pulled from. Asking the maintainer there might be the way to go

**Comment by mellester** [comment]
You can use the raw link direclty in your html 
https://raw.githubusercontent.com/factoriolab/factorio-lab/master/src/data/dsp/icons.png

**Comment by gamma-delta** [comment]
Nice, it uses the MIT license so I should be free to use them.
